// <auto-generated />
using System;
using Beyond.Todo.Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beyond.Todo.Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(TodoEFDbContext))]
    [Migration("20251128180113_SeedCategories")]
    partial class SeedCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beyond.Todo.Domain.Entities.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("Beyond.Todo.Infraestructure.Entities.TodoItemCategory", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.HasKey("Category");

                    b.ToTable("TodoItemCategories");

                    b.HasData(
                        new
                        {
                            Category = "Work"
                        },
                        new
                        {
                            Category = "Personal"
                        },
                        new
                        {
                            Category = "Learning"
                        });
                });

            modelBuilder.Entity("Beyond.Todo.Domain.Entities.TodoItem", b =>
                {
                    b.OwnsMany("Beyond.Todo.Domain.Entities.Progression", "Progressions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("Percent")
                                .HasColumnType("numeric");

                            b1.Property<int>("TodoItemId")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("TodoItemId");

                            b1.ToTable("Progression");

                            b1.WithOwner()
                                .HasForeignKey("TodoItemId");
                        });

                    b.Navigation("Progressions");
                });
#pragma warning restore 612, 618
        }
    }
}
