// <auto-generated />
using System;
using Beyond.Todo.Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beyond.Todo.Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(TodoEFDbContext))]
    [Migration("20251201164910_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beyond.Todo.Domain.Entities.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Work",
                            Description = "Progreso de la construcion de la aplicacion beyond todo.",
                            Title = "Construir el sistema Beyond Todo."
                        });
                });

            modelBuilder.Entity("Beyond.Todo.Infraestructure.Entities.TodoItemCategory", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.HasKey("Category");

                    b.ToTable("TodoItemCategories");

                    b.HasData(
                        new
                        {
                            Category = "Work"
                        },
                        new
                        {
                            Category = "Personal"
                        },
                        new
                        {
                            Category = "Learning"
                        });
                });

            modelBuilder.Entity("Beyond.Todo.Domain.Entities.TodoItem", b =>
                {
                    b.OwnsMany("Beyond.Todo.Domain.Entities.Progression", "Progressions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("Percent")
                                .HasColumnType("numeric");

                            b1.Property<int>("TodoItemId")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("TodoItemId");

                            b1.ToTable("Progression");

                            b1.WithOwner()
                                .HasForeignKey("TodoItemId");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    Date = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                                    Percent = 25m,
                                    TodoItemId = 1
                                },
                                new
                                {
                                    Id = 2,
                                    Date = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                                    Percent = 35m,
                                    TodoItemId = 1
                                },
                                new
                                {
                                    Id = 3,
                                    Date = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                                    Percent = 40m,
                                    TodoItemId = 1
                                });
                        });

                    b.Navigation("Progressions");
                });
#pragma warning restore 612, 618
        }
    }
}
